name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v3
      name: Install pnpm
      id: pnpm-install
      with:
        version: latest
        run_install: |
          - recursive: false
            args: [--no-frozen-lockfile]

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.2
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true

    - name: Build
      run: pnpm build
